CodeNerve/Let-Us-Java

Add Fibonacci numbers/BruteForce.java, Add Fibonacci numbers/Efficient.java
Added efficient and brute force code for adding Fibonacci numbers.
=> Create Add Fibonacci numbers code

MatrixOperations/Matrix.java, README.md
Matrix Initialization, Addition and Multiplication
=> Basic matrix operations added

MatrixOperations/Matrix.java
Added some more operations.
Fixed some bugs
=> Matrix Operations

Calculate Pi/CalculatePi.java, Calculate Pi/ReadMe.md
Add code to calculate pi using Java
=> Add Pi calculation code in Java

Dynammic Programming/HouseRobber.java, Dynammic Programming/ReadMe.md
=> Add House Robber DP code in Java

FindMinimumInRotatedSortedArray/FindMinimumInRotatedSortedArray.java, FindMinimumInRotatedSortedArray/ReadMe.md
Code to Find Minimum In Rotated Sorted Array
=> Add FindMinimumInRotatedSortedArray using binary search

Simple DES Encryption Algorithm/S_Des.java
This program accepts an 8-bit Plain Text(in binary) and a 10-bit Key(in binary) and outputs a Cipher Text of 8-bits(in binary).
It is a shortened version of the original 64-bit DES encryption algorithm.
=> Added Simple DES encryption algorithm implementation in Java

README.md
Also added my contribution topic to the contents list.
=> Added my name in the contributors list.

NoMatcher.java
If given input string is 'India' then it will print 'Matched'. Otherwise it will throw an exception called 'No Match Exception' with printing 'Not Matched'.
=> NoMatcher.java

Password Validation in Java/Password.java
This program has been implemented without using 'Regex'.
=> Added Password Validation program implementation in Java

admission.java
This java program basically represents an admission system of three colleges - TISL, NSEC and BIT. For each college we have a separate student type array which will store new admitted student name and department in each index position.
=> admission.java

armstrong-number/Armstrong-Number.java
get  given number is Armstrong or not.
=> Armstrong Number

Random interview questions/Top K frequent/ReadMe.md, Random interview questions/Top K frequent/TopKFrequent.java
- Add Top K frequent number question and solution
=> Add random interview questions

LeetCode Solutions/RemoveElement.java
Solution to the Leetcode problem 27
=> Add LeetCode solution folder with one solution

Pangram/Pangram.java
=> algorith for pangram sentences

EuclieanDistance/EuclieanDistance.java
=> euclidean distance for all dimensions

LongestPalindromicSubString/LongestPalindromicSubString.java
=> longest palindromic substring

codeQuotient2/bin/.gitignore, codeQuotient2/src/codeQuotient/Student.java, codeQuotient2/src/codeQuotient/TimeSpan.java, codeQuotient2/src/codeQuotient/add1toeachDigit.java, codeQuotient2/src/codeQuotient/aggMarks.java, codeQuotient2/src/codeQuotient/classRectangle.java, codeQuotient2/src/codeQuotient/cmpareReverse.java, codeQuotient2/src/codeQuotient/evenodd.java, codeQuotient2/src/codeQuotient/factorial.java, codeQuotient2/src/codeQuotient/hra.java, codeQuotient2/src/codeQuotient/kaperker.java, codeQuotient2/src/codeQuotient/leapYear.java, codeQuotient2/src/codeQuotient/matrixMultiplication.java, codeQuotient2/src/codeQuotient/max.java, codeQuotient2/src/codeQuotient/maxElement.java, codeQuotient2/src/codeQuotient/multiplication.java, codeQuotient2/src/codeQuotient/primenum.java, codeQuotient2/src/codeQuotient/sumArray.java, codeQuotient2/src/codeQuotient/sumofn.java, codeQuotient2/src/codeQuotient/swap.java
Hey there,
I am adding some codes of java named as CodeQuotient Java solution .
=> CodeQuotient Java solution

BubbleSort/BubbleSort.java
=> Bubble Sort

LinkedLists/SinglyLinkedLists/LinkedListOperations.java
Created various LinkedList operations for Create, delete, insert at front, append , display , length of linked list, search a node in Java. I hope this would be useful for the repository and to the community!
=> Added a separate folder LinkedLists and created  LinkedList opeartions-JAVA

BinaryTrees/MirrorTree.java
I have added a binary trees folder and added a solution for Mirror Tree
=> Added Binary Trees folder and added solution for Mirror Tree

LinkedLists/SinglyLinkedLists/DetectLoop_UsingHashMethod.java, LinkedLists/SinglyLinkedLists/ReverseLoop.java
I have added a solution for reverse a linked list and for detecting cycles in linked lists.
=> Added reversing a linkedlist and detecting cycles in linkedlist

Algorithms/src/main/java/sorting/InsertionSort.java
Added new Insertion sort algorithm ! Happy Hacktoberfest !
#3
=> Created Insertion sort algorithm

LeetCodeSolutions/src/main/java/Arranging Coins, LeetCodeSolutions/src/main/java/Arranging_Coins.java
You have a total of n coins that you want to form in a staircase shape, where every k-th row must have exactly k coins.
Given n, find the total number of full staircase rows that can be formed.
n is a non-negative integer and fits within the range of a 32-bit signed integer.
Example 1:
n = 5
The coins can form the following rows:
¤
¤ ¤
¤ ¤
Because the 3rd row is incomplete, we return 2.
Example 2:
n = 8
The coins can form the following rows:
¤
¤ ¤
¤ ¤ ¤
¤ ¤
Because the 4th row is incomplete, we return 3.
=> Arranging Coins in java

Algorithms/src/main/java/matrix_operation/Find2DMatrixSum.java
- Add code for finding 2d matrix sum
=> Find2DMatrixSum (add code for 2d matrix sum)

Algorithms/src/main/java/sorting/QuickSort.java
Creating QuickSort Alrogithm #3
=> Adding quicksort algorithm

LeetCodeSolutions/src/main/java/AddTwoNumbers.java, LeetCodeSolutions/src/main/java/LongestSubstringWithoutRepeatingCharacters.java
- Add leetcode solution for AddTwoNumbers
- Add leetcode solution for LongestSubstringWithoutRepeatingCharacters
=> Leetcode solutions (AddTwoNumbers, LongestSubstringWithoutRepeatingCharacters)

Constant_enum/src/main/java/Main.java
This PR contains Constant Enum Data Type in Java which can store list of constant data types in java.
=> Constant Enum data type in Java

Hackerrank/MatrixLayerRotation.java, Josephus Problem, Josephus_Problem.java
I have created a solution to Josephus problem which is a theoretical problem related to a certain counting-out game in which people are standing having a assigned number starting from 1. The problem describes that if starting from 1, it kills 2 and hand over the sword to 3, then 3 kills 4 and hands over the sword to 5. If this pattern continues in the circle until only one men is left, then who is the 'Last man Standing'?
=> Josephus problem

Small project/Calculator.java
This is another small calculator project I made.
=> Calculator.java

Games/Rock Paper Scissor.java
This is the very clean and playable code of rock paper scissor game. Give it a try!!
=> Create Rock Paper Scissor.java

LeetCodeSolutions/src/main/java/LRUCache.java, LeetCodeSolutions/src/main/java/LRU_Cache.java
=>  LRU_Cache.java

Games/guess_number_oops.java
i created the version of guess the number using oops , user has to enter a number in range 0-100 and computer will generate a random number if the number matches, user wins
=> guess_number_oops.java

Sorting/BubbleSort.java, Sorting/InsertionSort.java, Sorting/MergeSort.java, Sorting/SelectionSort.java
The folder consist of 4 most popular sorting techniques in an optimized manner such that it uses less resources and runs fast.
=> Optimized Some Of The Most Popular Sorting Techniques!

DigitalClock/DigitalClock.java
=> added digital clock

Algorithms/src/main/java/ThreeSum.java
=> Add ThreeSum

MatrixOperations/matrixmultiplication.java
I have added a java program in the 'MatrixOperations' folder.
The program does the following-->
- inputs number of rows and columns in matrix 1
- inputs number of rows and columns in matrix 2
- inputs elements in matrix 1
- inputs elements in matrix 2
- displays matrix 1
- displays matrix 2
- multiplies both the matrices
- displays the resultant matrix
This PR helps in issue- #1
=> Added program for Matrix Multiplication (Helps is issue #1 )

LeetCodeSolutions/Sudoku.java
Leetcode and GFG solution of sudoku problem
=> Sudoku.java

MatrixOperations/spiralshift.java
I have added a java program in the 'MatrixOperations' folder.
The program does the following-->
- inputs elements in the matrix
- performs spiral shifting on the elements of the matrix
- displays the resultant matrix
This PR helps in issue- #1
=> Added program performs spiral shifting in a matrix (Helps in issue #1 )

MatrixOperations/MatrixChainMultiplicationImplementation.java
Please have look on my java file.
=> Created and Added my MatrixChainMultiplicationImplementation.java

Recursion/ReverseNumber.java
I have created the reverse number program in java using recursion. I have added the program in the folder recursion. This helps in issue #1
=> Reverse Number

Wildcard Matching/Main.java, Wildcard Matching/ProblemStatement.txt
=> Wildcart Matching Problem #220

LeetCodeSolutions/ThreeSum.java
Please add my file to in your repository with label Hactoberfest
=> Solution of ThreeSum

Codeforces-Solution/WorkingWeek.java
Problem=Working Week  Codeforces Round #824 (Div. 2) Problem Link =https://codeforces.com/contest/1735/problem/A
=> Working Week Solution

LeetCodeSolutions/PowerofFour.java
i have added Solution for Power of four Question leetcode please merge it
=> i have added Solution for Power of four Question leetcode please merge it

LeetCodeSolutions/src/main/java/KthLargest.java, LeetCodeSolutions/src/main/java/KthLargestInArray.java
added algorithm to find Kth Largest in Array
=> hacktoberfest-2022

Buy_Seel_Stock_TA/Main.java, Buy_Seel_Stock_TA/Problem_Statement.txt
=> shivansh first commit

Hackerrank/LeftRotation.java
java Code for Left Rotation Question in Hackerrank
=> Added java Code for Left Rotation Question in Hackerrank

Numbers Programs/Palindrome Number.java
Hey I just added a new program to check if the number is palindrome or not.
Kindly review this program and merge it into main.
=> Added Palindrome Number

Arrange_Buildings/Main.java, Arrange_Buildings/Problem_Statement
=> Second commit

Algorithms/src/main/java/dynamic_programing/0 1 KNAPSACK.JAVA
DO MERGE IT PLEASE AS ITS FAMOUS DP PROBLEM
=> ADDED 0/1 KNAPSACK IN DP

Codeforces-Solution/ColorBlindness.java
Problem:Codeforces Round #817 (Div. 4)
Link: https://codeforces.com/contest/1722/problem/B
=> B.ColourBlindness Problem

arrays in java/array_binary_char.java, arrays in java/array_binary_int.java, arrays in java/array_binary_s.java, arrays in java/array_bubble_char.java, arrays in java/array_bubble_int.java, arrays in java/array_bubble_s.java
i have added a few programs in java related to arrays (integer, char and string types)(binary search and bubble sort )
=> basic array programs

LeetCodeSolutions/Algorithm_Day2_SquaresofaSortedArray.java, LeetCodeSolutions/Algorithm_Day3_MoveZeroes.java, LeetCodeSolutions/Algorithm_Day3_TwoSumIIInputArrayIsSorted.java, LeetCodeSolutions/Array_TwoSum.java, LeetCodeSolutions/BinarySearch.java, LeetCodeSolutions/FirstBadVersion.java, LeetCodeSolutions/LongestSubstringWithoutRepeatingCharacters.java, LeetCodeSolutions/MergeTwoBinaryTrees.java, LeetCodeSolutions/MiddleoftheLinkedList.java, LeetCodeSolutions/PermutationinString.java, LeetCodeSolutions/ReverseString.java, LeetCodeSolutions/ReverseWordsinaStringiII.java, LeetCodeSolutions/SearchInsertPosition.java
added more files in the "Leetcode solutions" directory.
=> Leetcode Solutions

Sorting/ComboSort.java, Sorting/ComboSorting.java, arrays in java/UniquePath.java
Added the solution to the UniquePath3 using backtracking method
=> Added the solution to CreateUniquePath  using Backtraking method

Count_Binary_Strings/Main.java, Count_Binary_Strings/Problem_Statement
=> 3rd commit

Graphs/Graph_implementation.java
Plz review my contribution, if it's ok then merge it. Thank you
=> Added a new program

LeetCodeSolutions/TrappingRainWater.java
I've completed issue #287 please review @Pradyuman7
=> Added Trapping rainwater Leetcode problem with 2 solutions

Fibonacciseries/FibonacciRecurse.java
It basically takes an input n to output the nth fibonacci number using recursion.
=> Created FibonacciRecurse,java

BinarySearch/OrderAgnosticBinarySearch.java
We all know that the basic requirement for Binary Search is that the array must be sorted. But for the array to be sorted it can be sorted in any order, that is, either descending or ascending order. So, in order agnostic binary search the searching algorithm is the same as we do in binary search of time complexity O(log n), it's just that we make a check to determine whether the array is sorted in ascending or descending order.
=> Created OrderAgnosticBinarySearch.java

Algorithms/src/main/java/NKnights.java
Java program that solves the NKnights problem.
=> Created NKnights.java

BinarySearch/BinaryRecurse.java
Binary Search using recursion in java.
=> Created BinaryRecurse.java

Goldmine/Main.java, Goldmine/Problem_Statement
=> 4th commit

competitive programming/FastIO.java
Added FastIO.java class which is a template used for faster IO-operations in Competitive Programming using Java.
=> Added FastIO.java class

Small project/TemperatureConverter.java
I think all issues have been resolved this time, thanks for the feedback!
=> A Celsius to Fahrenheit converter

Recursion/Power.java, Recursion/string.java
Hacktoberfest 2022 contribution
=> String Reverse using Recursion

GuessNumberGame/GuessNumber.java
=> Guessing a number game

Soduku_Solver/Sudoku.java
Created Sudoku Solver program in Java.
---
=> Sudoku Solver

Numbers Programs/HappyNumber.java, Numbers Programs/MersenneNumber.java
1.) Added a Java program to check whether a number is a Happy Number or Not
In number theory, a Happy Number is a number which eventually
reaches 1 when replaced by the sum of the square of each digit.
2.) Added a Java program to check whether a number is a Mersenne Number or Not
In mathematics, a Mersenne number is a number that is in the form of M(n)=2n-1.
Where n is an integer. It is an OEIS sequence A000225.
If n is prime, the corresponding Mersenne number may be prime and the number called Mersenne prime number.
It is an OEIS sequence A000043. It was given the name after the French mathematician Marin Mersenne.
=> Added HappyNumber program implementation in java

Snake Game with Various Features and GUI/GameFrame.java, Snake Game with Various Features and GUI/GamePanel.java, Snake Game with Various Features and GUI/README.md, Snake Game with Various Features and GUI/SnakeGamer.java
=> Added Snake Game with various Features and GUI

checkpalindrome/checkpalindrome.java
Java code to check whether a string is plaindrome or not .
---
=> checkpalindrome.java

Blockchain_Implementation/Block.java, Blockchain_Implementation/BlockStore.java, Blockchain_Implementation/Crypt.java, Blockchain_Implementation/isChainValid.java, Numbers Programs/PerfectNumber.java
Added Program to implement BlockChain Development in Java
Following stages of BlockChain Development are implemented:
->Block Creation
->Block Storage
->Hash Generation
->Block Validity Checker
=> Added Program to implement BlockChain Development in Java

Algorithms/KadaneAlgo.java
=> Added Kadane's Algorithm

FindFirstIndexOfNumber/findfirstindexofnumber.java
This is code to find first index where the number is present in an array . 
for example take an Array of size "5"
1 2 3 4 3
here the first occurence of 3 is at index "2" . So the program will output "2".
---
=> findfirstindexofnumber.java

LeetCodeSolutions/NextPermutation.java
=>  add Next Permutation

Numbers Programs/CatalanNumber.java
Added a Java program to print the Nth Catalan Number
In combinatorial mathematics, the Catalan numbers are a sequence of natural numbers
that occur in various counting problems, often involving recursively defined objects.
=> Added CatalanNumber program implementation in java

LeetCodeSolutions/ContainerMaxWater.java
=> Add Container Max Water java solution

LeetCodeSolutions/src/main/java/HouseRobber.java
=> house robber using DP added

Hackerrank/Java_Date_and_Time.java
Methods for converting between a specific instant in time and a set of calendar fields such as YEAR, MONTH, DAY_OF_MONTH, HOUR, and so on, and for manipulating the calendar fields, such as getting the date of the next week in java.
---
=> Enter date and get output the day.

LeetCodeSolutions/Russian Doll Envelopes/Russian_Doll_Envelopes.java
I have written the code in java for Russian Doll Envelopes.
---
=> Russian_Doll_Envelopes.java

LeetCodeSolutions/24 Game/24_Game.java
I have added the code of the 24 Game LeetCode problem.
---
=> 24_Game.java

Queue/Main.java
=> queue.java

LeetCodeSolutions/validAnagram.java
- [✔] Read through [contributing.md](https://github.com/CodeNerve/Let-Us-Java/blob/master/CONTRIBUTING.md)
- [✔] All the code files are in a relevant directory
- [✔] Code is only in java (and the files have .java extension), no other files (e.g. .class files) are included
- [✔] The code is not already present in the repository
- [✔] The contribution is meaningful and not just a simple print statement
- [✔] The build passes for your PR
---
=> add valid anagram

LeetCodeSolutions/LFU Cache.java
I have added the code of LFU cache problem from leetcode.
---
=> LFU Cache.java

AllIndicesOfNumber/allindicesofnumber.java
This is code to print all indices of a number . For example take and array of size "5". and the elements of array are " 2 ,7 ,2 ,10, 2 " .  This will print " 0 ,  2 , 4 .
---
=> allindicesofnumber.java

LeetCodeSolutions/Wildcard Matching.java
I have added the code of the wildcard matching problem from leetcode
---
=> Wildcard Matching.java

LeetCodeSolutions/Decode Ways II .java
I have added the code of decode ways II problem from leetcode
---
=> Decode Ways II.java

LeetCodeSolutions/Reconstruct Itinerary.java
I have added the code of  Reconstruct Itinerary problem of leetcode
---
=>  Reconstruct Itinerary.java

LeetCodeSolutions/Cut Off Trees for Golf Event.java
I have added the code of Cut Off Trees for Golf Event problem of leetcode in java. I also, paste the question link.  Thank You.
---
=> Cut Off Trees for Golf Event.java

LeetCodeSolutions/Number_of_ways_of_cutting_a_pizza.java
This code is solution of leetcode problem Number of ways of cutting a pizza.
---
=> Number_of_ways_of_cutting_a_pizza.java

LeetCodeSolutions/Random_pick_with_blacklist.java
This is solution to the problem random pick with blacklist from leetcode.
---
=> Random_pick_with_blacklist.java

LeetCodeSolutions/Allocate_Mailboxes.java
I have added java code to the problem Allocate Mailboxes from leetcode.
---
=> Allocate_Mailboxes.java

interviewQuestions/ArrayOccurencesMinMoves.java, interviewQuestions/LeapingFrog.java
=> Add two Java coding interview questions

Games/Hangman.java
Create a  hangman game using java
---
=> Pull request for hactoberfest.

Games/Pin_Ball.java
A simple pinball game that is made in java
---
=> A pin ball game made in java

BinarySearch/BSInInfiniteArray.java
This is an algorithm on the application of binary search while assuming the array to be infinite
---
=> Added BSInInfiniteArray.java

Fibonacciseries/FibonacciJavaStreams.java
=> Add FibonacciJavaStreams.java

Algorithms/CyclicSort.java
added algorithm of cyclic sort
---
=> Added CyclicSort.java

LeetCodeSolutions/SplitArray.java
added a leetcode problem with its solution
---
=> added SplitArray.java

Algorithms/BreadthFirstSearch.java
=> Add `BreadthFirstSearch.java`

MatrixOperations/MatrixUtil.java
=> Add `MatrixUtil.java`

Algorithms/DepthFirstSearch.java
=> Add `DepthFirstSearch.java`

LeetCodeSolutions/SetMismatch.java
added a leetcode problem with its solution
---
=> added SetMismatch.java

Small project/Multiplication.java
a small objective multiplication table
=> A multiplication table

LeetCodeSolutions/src/main/java/MinimumPathSum.java, LeetCodeSolutions/src/main/java/SearchInRotatedSortedArray.java
---
- [x ] The PR has meaningful contribution to make the repository better and not just typos or such small changes
=> search in rotated sorted array added

Intresting_games/Number_of_ways_in_a_Maze.java, Recursion/JosephusProblem.java
Added code for the Josephus problem and the number of all possible ways in a maze using recursion.
=> Codes using recursion.

LeetCodeSolutions/Word Ladder || .java
I have added the code of Word Ladder || problem from Leetcode. please merge it. Thank you
---
=> Word Ladder || .java

LeetCodeSolutions/Word Break ||.java
I have added the code of Word Break || problem from Leetcode. I also paste the question link.
---
=> Word Break ||.java

LeetCodeSolutions/Word Search II .java
I have added the code of word search II problem of leetcode. please merge it. Thank You
---
=> Word Search II.java

LeetCodeSolutions/Freedom Trail.java
I have added the code of Freedom Trail problem of leetcode.
please merge it.
Thank You
---
=> Freedom Trail.java

LeetCodeSolutions/Stickers to Spell Word.java
I have added the code of Stickers to spell Word problem of leetcode. please merge it. Thank you.
---
=> Stickers to Spell Word.java

Hashing_Implementation/Hashing.java
Might help if anyone needs a revision of HashSet and HashMap. :)
=> Added code which explains Hashset and HashMap implementation.

LeetCodeSolutions/MaxSubarray.java
Here is the question--> 
**Given an integer array `nums`, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum. Given an integer array `nums`, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.**
=> Added code which finds the largest sum possible from a sub array.

LeetCodeSolutions/Trailing_zeroes.java
Did this using two approaches, I hope you find it useful.
=> Added code which finds the trailing zeroes in the factorial of a number.

Numbers Programs/all_subsets_of_first_n_natural_numbers.java
**This code finds subsets of n natural numbers using recursion.**
=> Added code which finds subsets of first n natural numbers.

LeetCodeSolutions/Maximal Rectangle.java
I have added the code of Maximal Rectangle problem of leetcode.   I also added the question link. 
Please merge it.  Thank You.
---
=> Maximal Rectangle.java

LeetCodeSolutions/Couples Holding Hands.java
I have added the code of couple Holding Hands from leetcode problem.  I also add the question link
please merge it.
Thank you.
---
=> Couples Holding Hands

LeetCodeSolutions/Prefix and suffix Search.java
I have added the code of Prefix and suffix Search problem of leetcode . I also add question link. please merge it.
Thank you.
---
=> Prefix and suffix search.java

LeetCodeSolutions/Distinct Subsequences.java
I have added the code of Distinct Subsequences problem of leetcode. I also added the question link. please merge it.  Thank you
---
=> Distinct Subsequences.java

LeetCodeSolutions/Concatenated Words.java
I have added the code of Concatenated Words problem of leetcode. I also added the question link. please merge it. Thank You.
---
=> Concatenated Words.java

LeetCodeSolutions/First_Missing_Positive.java
I have  added the code of First missing positive problem of leetcode  I also added question link. Please merge It.   Thank You.
---
=> First_missing_positive.java

LeetCodeSolutions/Basic calculator IV.java
I have  added the code of Basic calculator problem of leetcode  I also added question link. Please merge It.   Thank You
---
=> Basic-calculator-iv

Hackerrank/Java_currency_formatter.java
=> Added Java_currency_formatter.java
